// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvyBnOqMKu5C3gQbK82KI_f87g3ME3Tow',
    appId: '1:996273313700:web:322c26c8fc88c092349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    authDomain: 'taxiappz-new.firebaseapp.com',
    storageBucket: 'taxiappz-new.firebasestorage.app',
    measurementId: 'G-KVX7FEZRTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9xkY1n-WGQpUBjaWeWYv0crwo57RhGuU',
    appId: '1:996273313700:android:502ac907955fb3c0349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    storageBucket: 'taxiappz-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJe9Elc_rkbAXgNFPFupy9jC-Wh04Xyb4',
    appId: '1:996273313700:ios:29c574ec096901aa349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    storageBucket: 'taxiappz-new.firebasestorage.app',
    iosBundleId: 'com.taxiappzdriver.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJe9Elc_rkbAXgNFPFupy9jC-Wh04Xyb4',
    appId: '1:996273313700:ios:8ca61be6c93ede08349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    storageBucket: 'taxiappz-new.firebasestorage.app',
    iosBundleId: 'com.taxiappz.client.taxiAppz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPUKDpER6aOi5Pjndhjz64Wj_-kMT7FEw',
    appId: '1:996273313700:web:76fd658503c43805349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    authDomain: 'taxiappz-new.firebaseapp.com',
    storageBucket: 'taxiappz-new.firebasestorage.app',
    measurementId: 'G-V1LMVLJYN6',
  );

}