// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvyBnOqMKu5C3gQbK82KI_f87g3ME3Tow',
    appId: '1:996273313700:web:322c26c8fc88c092349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    authDomain: 'taxiappz-new.firebaseapp.com',
    storageBucket: 'taxiappz-new.firebasestorage.app',
    measurementId: 'G-KVX7FEZRTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9xkY1n-WGQpUBjaWeWYv0crwo57RhGuU',
    appId: '1:996273313700:android:214903919aa35837349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    storageBucket: 'taxiappz-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJe9Elc_rkbAXgNFPFupy9jC-Wh04Xyb4',
    appId: '1:996273313700:ios:1d88c08b6b6b3819349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    storageBucket: 'taxiappz-new.firebasestorage.app',
    iosBundleId: 'com.taxiappzuserpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJe9Elc_rkbAXgNFPFupy9jC-Wh04Xyb4',
    appId: '1:996273313700:ios:27c7eae6285dc968349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    storageBucket: 'taxiappz-new.firebasestorage.app',
    iosBundleId: 'com.example.taxiAppUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5nCe7_Xut51Jjn1mx1FfLV34sC4rZzJk',
    appId: '1:996273313700:web:51cd5ee94e9718dc349331',
    messagingSenderId: '996273313700',
    projectId: 'taxiappz-new',
    authDomain: 'taxiappz-new.firebaseapp.com',
    storageBucket: 'taxiappz-new.firebasestorage.app',
    measurementId: 'G-H25LW9LXDJ',
  );

}