
export const SCREEN_NAMES = {
  Admin: 'admin',
  User: 'user',
  Driver: 'driver',
  Pakage: 'pakage',
  Sidemnu: "sidemenu",
  Dashboard: "dashboard",
  Category: "category",
  Vehicle: "vehicle",
  VehicleModel: "vehiclemodel",
  GroupDocument: 'groupdocument',
  Document: 'document',
  Roles: 'roles',
  Permission: 'permission',
  Privillage: 'privillage',
  Language: 'language',
  Country: 'country',
  Translation: 'translation',
  ProjectVersion: 'projectversion',
  Client: 'client',
  Subscription: 'subscription',
  IntroScreen: "introscreen",
  RideNow: "ridenow",
  RideLater: "ridelater",
  Cancellation: "cancellation",
  InvoiceQuestion: "invoicequestion",
  Promo: "promo",
  FormData: "formdata",
  DocumentExpiry: "documentexpiry",
  DriverSummary: "driversummary",
  CompletedLocalTrip: "completedlocaltrip",
  CompletedRentalTrip: "completedrentaltrip",
  DriverReports: "driverreports",
  TripReports: "tripreports",
  DriverWallet: "driverwallet",
  TripWiseReports: "tripwisereports",
  QuestionReports: "questionreports",
  PromoUseReports: "promousereports",
  Email: "email",
  Dispatcher: "dispatcher",
  Dispatch: "dispatch",
  Invoice: "invoice",
  RentalList: 'rentallist',
  Rental: "rental",
  Faq: "faq",
  Ticket: "ticket",
  Wallet: "wallet",
  Complaints: "complaints",
  TranslationMaster:"translationmaster",
  Settings: "settings",
  FleetManagement: "fleetmanagement",
  DemoClient : "demoClient"
};


export const ROLE = {
  SuperAdmin: 'Superadmin',
  Dispatcher: 'Dispatchers',
  Client: 'Client',
  Demo: 'Demo'
};
